Vagrant.configure("2") do |config|

  # machine
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/stream8"
    centos.vm.hostname = "centos"
  end

  # provision
  config.vm.provision "podman" do |container|
    container.run "web01",
      image: "docker.io/library/httpd:latest",
      args: "-d -t -p 80:80"
  end
end

