Vagrant.configure("2") do |config|

  # libvirt
  config.vm.provider "libvirt" do |lv|
    lv.cpus = 2
    lv.memory = 2048
    # libvirt.qemu_use_session = false
  end

  # virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
    vb.linked_clone = true
  end

  # hyper-v
  config.vm.provider "hyperv" do |hv|
    hv.cpus = 2
    hv.memory = "1024"
    hv.maxmemory = "2048"
    hv.linked_clone = true
  end

  # machine
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "fedora/34-cloud-base"
    fedora.vm.hostname = "fedora"
  end

  # provision
  config.vm.provision "shell" do |shell|
    shell.inline = "sudo dnf update -y"
    shell.reboot = "true"
  end
end
