Vagrant.configure("2") do |config|

  # machine
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/stream8"
    centos.vm.hostname = "centos"
  end

  # provision
  config.vm.provision "podman" do |container|
    container.build_image "/vagrant/",
      args: "-t localhost/fedora-web"
    container.run "localhost/fedora-web",
      args: "-d -t -p 80:80"
  end
end

